"""checking alembic

Revision ID: ab078e979b5f
Revises: a2b3de25b990
Create Date: 2024-04-24 08:06:31.147365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab078e979b5f'
down_revision: Union[str, None] = 'a2b3de25b990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('email_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('header', sa.VARCHAR(length=255), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('footer', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('openai_key', sa.VARCHAR(length=500), nullable=True),
    sa.Column('payment_intent_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amount', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
